### ISSUE TITLE
Submit docker submission using Synapse python API

### ISSUE THREAD

**Issue by Simon-Harris-IBM** [Simon-Harris-IBM/ObjectNetChallenge-Workflows#36]
I'm trying to write a small python script that will submit a docker image for evaluation a number of times:

```
import synapseclient

syn = synapseclient.Synapse()
syn = synapseclient.login('SimonHarris','blahblah!')

eval_q = syn.getEvaluation(9614430)
docker_img = syn.get('syn21644258')

docker_img['dockerTag'] = "sha256:a0a104ae0dd51773df58498d70d6f2a28f5d7076c9b2c80a09afe83dd0c99944"
docker_img['docker_tag'] = "sha256:a0a104ae0dd51773df58498d70d6f2a28f5d7076c9b2c80a09afe83dd0c99944"
docker_img['docker_digest'] = "sha256:a0a104ae0dd51773df58498d70d6f2a28f5d7076c9b2c80a09afe83dd0c99944"
docker_img['dockerDigest'] = "sha256:a0a104ae0dd51773df58498d70d6f2a28f5d7076c9b2c80a09afe83dd0c99944"

print("Submitting to evaluation q: ", eval_q)
print("Submitting docker image: ", docker_img)

for x in range(1,2):
  n = 'From submission.py: ' + str(x)
  print("Submission: ", str(x))
  sub = syn.submit(eval_q, docker_img, name=n)
  print(sub)
  time.sleep(5)
```

I get the following error:
Traceback (most recent call last):
  File "submit.py", line 23, in <module>
    sub = syn.submit(eval_q, docker_img, name=n)
  File "/Users/simon/miniconda2/lib/python2.7/site-packages/synapseclient/client.py", line 2363, in submit
    submitted = self._submit(submission, entity['etag'], eligibility_hash)
  File "/Users/simon/miniconda2/lib/python2.7/site-packages/synapseclient/client.py", line 2381, in _submit
    submitted = self.restPOST(uri, json.dumps(submission))
  File "/Users/simon/miniconda2/lib/python2.7/site-packages/synapseclient/client.py", line 3469, in restPOST
    exceptions._raise_for_status(response, verbose=self.debug)
  File "/Users/simon/miniconda2/lib/python2.7/site-packages/synapseclient/exceptions.py", line 153, in _raise_for_status
    raise SynapseHTTPError(message, response=response)
synapseclient.exceptions.SynapseHTTPError: 400 Client Error:
Docker Digest cannot be null

I've searched the code and docs and can't find a mention of 'Docker Digest'. I also added a number of guesses into the docker_image variable, but nothing seems to work.

Can you advise please ?

**Comment by thomasyu888** [comment]
@Simon-Harris-IBM.  Theres good and bad news.

The good news is I actually contributed this feature into the client quite some time ago.

The bad news is that it's in the develop branch.  We are currently working on the `v2.0` release, but I don't have a timeline for when the release will come out.

```
import synapseclient
synapseclient.__version__
'2.0.0.dev0'
syn = synapseclient.login()
evaluation = syn.getEvaluation(9614111)
docker = syn.get("syn20717986")
syn.submit(evaluation, docker, dockerTag="ping")
```

**Comment by Simon-Harris-IBM** [comment]
Drat! Will have to be back to button clicks then....

**Comment by thomasyu888** [comment]
@Simon-Harris-IBM The release is going to happen really soon.  I am hoping by end of this week, so this is plausible.

**Comment by Simon-Harris-IBM** [comment]
yeeehaaaaa .....

**Comment by thomasyu888** [comment]
@Simon-Harris-IBM python client v2.0.0 is out.  The usage of submit docker is above.
